## MATRIKS

In [1]:
import numpy as np

In [2]:
A=np.array([[1,2],[3,4],[5,6]])
A
# memiliki baris dan kolom adalah perbedaan matrixdibanding vektor


array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
A.shape
# memperlihatkan berapa baris dan kolom


(3, 2)

Tipe matrix ada 4
- square matrix             X=np.array([[1,2,3],[3,4,5],[5,6,7]])
- upper triangle matrix     np.triu(X)
- lower triangle matrix     np.tril(X)
- diagonal matrix           np.diag(X)
- identity matrix           np.eye(shape)

In [21]:
# Contoh
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
A[1]

array([4, 5, 6])

In [15]:
# jika ingin mengaksesdata khusu baris-kolom
A[1][2]
A[1,2]

6

In [18]:
A[:,2]
A[:,-1]

array([3, 6, 9])

In [71]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Operasi Aritmatika dalam matriks
- penjumlahan
- pengurangan 
- pembagian
- perkalian

In [26]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
# jangan lupa kurungsiku ada 2 kalau membentuk data 2D
B=np.array([[1,2,0],[4,1,3],[2,5,0]])
B

array([[1, 2, 0],
       [4, 1, 3],
       [2, 5, 0]])

Penjumlahan

In [29]:
A+B

array([[ 2,  4,  3],
       [ 8,  6,  9],
       [ 9, 13,  9]])

In [30]:
10+B

array([[11, 12, 10],
       [14, 11, 13],
       [12, 15, 10]])

Pengurangan

In [31]:
A-B

array([[0, 0, 3],
       [0, 4, 3],
       [5, 3, 9]])

In [32]:
10-A

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

Pembagian

Perkalian

In [33]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# perkalian dengan skalar
A*10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# perkalian dengan hadamard product
A*np.eye(3)

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [37]:
# perkalian dot product
J=np.array([[1,2,0],[0,3,1],[1,0,0]])

K=np.array([[0,1],[1,2],[0,1]])

In [38]:
J

array([[1, 2, 0],
       [0, 3, 1],
       [1, 0, 0]])

In [39]:
K

array([[0, 1],
       [1, 2],
       [0, 1]])

In [40]:
J @ K

array([[2, 5],
       [3, 7],
       [0, 1]])

In [42]:
L=np.array([[3,1,7],[4,5,6]])
K=np.array([[2],[1],[0]])

In [43]:
L

array([[3, 1, 7],
       [4, 5, 6]])

In [44]:
K

array([[2],
       [1],
       [0]])

In [48]:
H=L@K
H


array([[ 7],
       [13]])

In [49]:
H.shape

(2, 1)

## Transpose
mengubah kolom menjadi baris dan baris menjadi kolom dengan diputar 90 derajat

Tinggal menambah .T di belakang sebagai atribut Transpose

In [50]:
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Inverse
suatu matriks dikalikan dengan inverse, hasilnya adalah matriks identitas

In [52]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
B

array([[1, 2, 0],
       [4, 1, 3],
       [2, 5, 0]])

In [56]:
inv_B=np.linalg.inv(B)
inv_B

array([[ 5.00000000e+00,  1.54197642e-17, -2.00000000e+00],
       [-2.00000000e+00, -6.16790569e-18,  1.00000000e+00],
       [-6.00000000e+00,  3.33333333e-01,  2.33333333e+00]])

In [57]:
np.linalg.det(B)

-2.9999999999999996

In [63]:
C=np.array([[1,2],[3,6]])
np.linalg.inv(C)

array([[-1.80143985e+16,  6.00479950e+15],
       [ 9.00719925e+15, -3.00239975e+15]])

## Tensor
multi dimensional array ( N-D array)

In [67]:
X = np.array([[1,5,1,3],[3,7,2,1]])
Y = np.array([[5,1,2,5],[5,1,0,0]])
Z = np.array([[0,6,1,0],[3,1,0,0]])

In [65]:
# matriks yg menjadi tensor shapenya harus sama semua
X.shape

(2, 4)

In [68]:
tensor=np.array([X,Y,Z])
tensor

array([[[1, 5, 1, 3],
        [3, 7, 2, 1]],

       [[5, 1, 2, 5],
        [5, 1, 0, 0]],

       [[0, 6, 1, 0],
        [3, 1, 0, 0]]])

In [69]:
tensor.shape

(3, 2, 4)

3 data, 2 baris, 4 kolom