## Numpy


In [1]:
import numpy as np

In [90]:
tinggi = [1.7, 1.8, 1.9, 1.10, 1.11, 1.12]
berat = [60.5, 61.5, 62.5, 63.5, 64.5, 65.6]

berat/tinggi

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [91]:
np_tinggi= np.array(tinggi)
np_berat = np.array(berat)

np_berat/np_tinggi

array([35.58823529, 34.16666667, 32.89473684, 57.72727273, 58.10810811,
       58.57142857])

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
print(np.arange(3,10,2))

[3 5 7 9]


In [14]:
arr=np.array([1,2,3,4])
arr_new=np.append(arr,[7,8,9])

In [15]:
arr_new

array([1, 2, 3, 4, 7, 8, 9])

In [16]:
np.delete(arr_new,3)

array([1, 2, 3, 7, 8, 9])

## 0-D/Skalar

In [10]:
arr=np.array(6)
print(arr)

6


In [11]:
arr.ndim
# skalar

0

In [12]:
arr.shape

()

## 1-D/Vektor

In [13]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [17]:
arr.ndim

1

In [18]:
arr.shape

(4,)

## 2-D/Matriks

In [20]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
arr.ndim

2

In [22]:
arr.shape

(2, 4)

## Latihan

In [23]:
arr=np.array([[[1,2,3,4]]])
print(arr)

[[[1 2 3 4]]]


In [24]:
arr.ndim

3

In [25]:
arr.shape

(1, 1, 4)

In [27]:
arr.size # mengetahui jumlah keseluruhan data

4

In [32]:
arr=np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [31]:
matriks=arr.reshape(3,2)
print(matriks)


[[0 1]
 [2 3]
 [4 5]]


In [40]:
matriks2=arr.reshape(6,1)
print(matriks2)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [50]:
a=np.array([1,2,3,4,5,6])
print(a.shape)
print(a)

(6,)
[1 2 3 4 5 6]


In [51]:
a2=a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [52]:
a3=a[:,np.newaxis]
print(a3.shape)
print(a3)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [53]:
a_e=np.expand_dims(a, axis=1)
a_e.shape

(6, 1)

In [92]:
a_e

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [102]:
a_e2= np.expand_dims(a, axis=0)
a_e2.shape[0]

1

In [103]:
a_e2

array([[1, 2, 3, 4, 5, 6]])

## SOAL


In [54]:
arr=np.array([1,2,7,4,10,5])
print(arr[2:6])

[ 7  4 10  5]


In [65]:
arr=np.array([1,2,7,4,10,5,13,11])
print(arr[2:8:3])

[7 5]


In [56]:
arr=np.array([1,2,7,4,10,5,13,11])
print(arr[:8:3])

[ 1  4 13]


In [57]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[0,2]) # dari siku pertama lalu indeks ke 2 yaitu 3

3


In [61]:

print(arr[2,2:4])

[11 12]


In [70]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[1:2,3])

[8]


In [73]:
arr=np.array([[1,2,3,4,8,10],[5,6,7,8,7,10],[9,10,11,12,11,12]])
print(arr[:4:2,2])
print(arr[1:2,2:3])

[ 3 11]
[[7]]


In [74]:
print(arr[arr>=3])

[ 3  4  8 10  5  6  7  8  7 10  9 10 11 12 11 12]


In [75]:
arr_cek=arr[arr>=3]
arr_cek.ndim

1

In [104]:
a_1 = np.array([[1,1],
                [2,2]])

a_2 = np.array([[3,3],
                [4,4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [105]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [81]:
arr_new=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=arr_new.reshape(2,3,-1) # unknown dimension (-1)
print(new_arr.shape)
print(new_arr)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


[['bear', 'bat'], ['deer', 'fox']]
